### ISSUE TITLE
Error importing Barbarian-Totem Warrior

### ISSUE THREAD

**Issue by ThijsBoehme** [safety-orange/Imports-for-MPMB-s-Character-Sheet#1]
I'm trying out the new v12.999 sheet with the scripts on this repo, but I'm encountering this error when importing the published material (both full and minified):
`TypeError: ClassSubList['barbarian-totem warrior'] is undefined`

**Comment by adamdva** [comment]
The AmendTotemWarriorSCAG function in the all_WotC_published is declared before 'barbarian-totem warrior' is added, and causes this error. If you move the function declaration down, it works.
I did this to my local copy.

**Comment by safety-orange** [comment]
Thank you for reporting this issue, it has been fixed in [this commit](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/commit/633f92a9e713d653afc946884cb7d9c42cd194f4).
