### ISSUE TITLE
Clumsily written sentence in Divine Sorcerer

### ISSUE THREAD

**Issue by Smashman** [safety-orange/Imports-for-MPMB-s-Character-Sheet#12]
https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/cfe69a0b89b8dd656d9f88973321debcfd896edf/WotC%20material/pub_20171121_XGtE.js#L1927

I see why it's written differently to the others, but I am sure there's a grammatically better way of saying this?

Also, what is the recommended character limit per line?

**Comment by safety-orange** [comment]
What alternative do you suggest?

There is no hard character limit per line, as the fonts used have different widths for different characters. The only way is to test it out on the colourful character sheets (as they have a narrower field for Class Features).

**Comment by safety-orange** [comment]
Fixed [here](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/commit/10d4ede211302e2283e2bb44c35198b06fc0f93e).

**Comment by Smashman** [comment]
That works, thanks. 👍
