### ISSUE TITLE
Unearthed Arcana: Elf Subraces - Shadar kai

### ISSUE THREAD

**Issue by magnusprime27** [safety-orange/Imports-for-MPMB-s-Character-Sheet#13]
the shadar kai is missing some info in its blessing of the raven queen feature, unless deliberate.
it tells what it does in the traits section, but  maybe the ability doesn't need the desc?

    "blessing of the raven queen" : {
			name : "Blessing of the Raven Queen",
			minlevel : 1,
			usages : 1,
			recovery : "short rest",
			tooltip : "",
			action : ["bonus action", ""]
		}

**Comment by safety-orange** [comment]
I first thought you are posting an updated feature code for the race, but it seems that you just copy-pasted exactly [what is in the file of this repo](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/master/WotC%20material/ua_20171113_Elf-Subraces.js#L145-L152). What change do you suggest?

With "but maybe the ability doesn't need the desc?" are you trying to say that the feature should have a 'description' attribute?
You should know that racial features don't have 'description' attributes, and that it is explicitly not part of the syntax for races. Racial features are different than class features, even though they use a lot of the same syntax. Adding a description to a racial feature will accomplish exactly nothing, as that attribute is not used anywhere. Explanations of racial features go in the racial traits section, exactly as has been done with the Shadar-Kai.
