### ISSUE TITLE
Spell description bugs. (Toll the dead & Tsunami)

### ISSUE THREAD

**Issue by DandD-gitstuff** [safety-orange/Imports-for-MPMB-s-Character-Sheet#16]
Toll the Dead (cantrip) says it is a Constitution save, should be Wisdom.
Tsunami (8th level spell) says it has a casting time of 1 action, when it should be 1 minute.

**Comment by safety-orange** [comment]
I don't know what stuff you are using, but none of the things you mention are wrong in this repository.

Toll the Dead says it has a Wisdom save, I don't know why you think it says Constitution. Just look at the [code here for XGtE](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/master/WotC%20material/pub_20171121_XGtE.js#L4075) and [here for the UA version](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/master/WotC%20material/ua_20170403_Starter-Spells.js#L206)...

The spell Tsunami is also correctly listed as having a 1 min casting time, [just look at the code](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/master/WotC%20material/pub_20140818_PHB.js#L4052)...

Perhaps you imported something into your sheet from another origin than this repository?
