### ISSUE TITLE
Druid Spells not Appearing.

### ISSUE THREAD

**Issue by CandiedAcorns** [safety-orange/Imports-for-MPMB-s-Character-Sheet#17]
When it asks to automatically create a spell sheet for the Druid (Circle of the Moon) and I click ok, it only gives me options to fill in cantrips.

**Comment by safety-orange** [comment]
First off all, that seems more like an issue with the sheet than with the import material in this GitHub. For issues with the sheet, contact morepurplemorebetter at [his GitHub](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet).

Second, the spell selection dialog only shows things where you have an actual choice. As the druid can cast all the spells on its list, there is no reason for that dialog to have you select any spells. Did you continue with generating a spell sheet? Was the spell sheet also empty? I'm guessing the spell sheet generates fine and you were just confused by the fact that you don't select your prepared spells in the spell selection dialog, but on the generated spell sheet page.

I'm closing this 'issue', but you are welcome to open a new one at MPMBs GitHub if you think the sheet is not working as it should. I would recommend adding a screenshot or something of both the spell selection dialog and the generated spell sheet to illustrate the problem. Also, you should really mention the version of the sheet and Adobe Acrobat that you are using.
