### ISSUE TITLE
Wayfinder's Guide to Eberron?

### ISSUE THREAD

**Issue by Smashman** [safety-orange/Imports-for-MPMB-s-Character-Sheet#20]
Contains:

- 4 Races
- 24 Subraces
- 13 Backgrounds
- 14 Feats
- 64 Magic Items
- 1 Monster

Wondering if you'd be interested in splitting this work up? Don't think it's fair for you to do it all!

Additionally [the latest UA](http://dnd.wizards.com/articles/unearthed-arcana/races-eberron) contains the 4 races mentioned above.

**Comment by safety-orange** [comment]
The UA part was already finished before I saw this comment ;)

As for the rest of WGtE, all that is left to do is the 4th chapter, Dragonmarks. I will take a swing at it tomorrow (it is already evening where I'm at). If anybody wants to work on it in the meantime, please let me know your progress! There is a thread for this on reddit: https://www.reddit.com/r/mpmb/comments/91b6p1/the_new_eberron_module/

**Comment by Smashman** [comment]
Well it turns out that you are a machine of the highest order.

**Comment by SoilentBrad** [comment]
Starting the House Agent background(s) now.

**Comment by safety-orange** [comment]
The backgrounds and all the dragonmarked subraces/variants are now finished.

All that is left are the feats: Greater Dragonmark and Aberrant Dragonmark

**Comment by safety-orange** [comment]
Everything is done (except the magic items, but there is no way to do them...)!

Closing this 'issue' :)
