### ISSUE TITLE
Repeated spells and cantrips

### ISSUE THREAD

**Issue by Fontanapink** [safety-orange/Imports-for-MPMB-s-Character-Sheet#22]
1st lvl druid spell:
Snare

Cantrips:
Infestation
Primal Savagery

**Comment by RobRoseKnows** [comment]
Uh, can you elaborate?

**Comment by Fontanapink** [comment]
Yeah! sorry about that.

When you are choosing cantrips and spells, some of them are repeated. I don't know if that's something specific from mpmb or here

**Comment by Shwaffle** [comment]
This looks like a possible duplicate of the other open issue as well.

I believe this is specific to the sheet, and has been addressed in v13: https://www.reddit.com/r/mpmb/comments/81vqbp/three_subclasses_double_spells/

**Comment by Fontanapink** [comment]
Cool! I'll just go ahead and close the issues.

BTW THANK YOU SO MUCH FOR YOUR WORK!!!! Everything is AMAZING
