### ISSUE TITLE
Blood Hunter (Order of the Profane Soul) hanging on Unsealed Arcana at upgrade to Level 15

### ISSUE THREAD

**Issue by revgizmo** [safety-orange/Imports-for-MPMB-s-Character-Sheet#23]
I'm having trouble with all 3 versions of the pdf: upon trying to Upgrade to level 15 for a Blood Hunter (Order of the Profane Soul), the update hangs indefinitely on "Updating to Blood Hunter (Order of the Profane Soul)'s Unsealed Arcana..."

I don't see an error message or any other way to identify the error.  I looked at the js file, and it appears consistent with Revealed Arcana, which ran fine at level 7.

**Comment by safety-orange** [comment]
There is no Blood Hunter script in this repository. You are probably looking for [the one on MPMB's repository](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content/Classes/Blood%20Hunter%20%5BMatthew%20Mercer's%20work%2C%20transcribed%20by%20Darryl%20%26%20MPMB%5D.js). Please report it there.

As this script is beyond what I have control over, I'm closing this issue.

**Comment by revgizmo** [comment]
You are awesome
