### ISSUE TITLE
Dragonmark, Healing (Halfling) hanging up

### ISSUE THREAD

**Issue by wdwyes2000** [safety-orange/Imports-for-MPMB-s-Character-Sheet#24]
When selecting a class after choosing Dragonmark, Healing (Halfling) for the race, causes the sheet to hang up with the following message.  When choosing class first, the hang up occurs when selecting the race.

![healing](https://user-images.githubusercontent.com/42478563/44284566-01074000-a217-11e8-9e12-e9836238cb39.png)

**Comment by safety-orange** [comment]
Thank you for reporting this issue! This has now been resolved by [the latest commit](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/commit/fa41a4f027fc237d9dfe95abf70e7952ae5d5fce).
