### ISSUE TITLE
Missing data from MM

### ISSUE THREAD

**Issue by aga9** [safety-orange/Imports-for-MPMB-s-Character-Sheet#26]
As title: the Wildshapes sheet is missing a few MM data from the drop-down list: Giant Ape, Tyrannosaurus Rex.

**Comment by safety-orange** [comment]
First of all, neither the Giant Ape nor the Tyrannosaurus Rex are part of this repository. Both creatures are part of the SRD and thus part of the base sheet. See [MPMB's GitHub for those](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_variables/ListsCreatures.js#L2240-L2277). Thus there data is not missing and you can select them on the Companion page without issue.

Second, I suspect that the reason that neither are listed on the Wild Shape pages is that both have a Challenge Rating above 6, the highest CR that a Druid (Circle of the Moon) can use for Wild Shape. Thus, neither creatures will ever be needed on the Wild Shape pages by RAW and are thus not part of the dropdown boxes or selectable through the menu.
However, you can still use those creatures by typing in their full name into a Wild Shape entry.

If you still think this is an omission that should be addressed, please contact MPMB (by posting to his GitHub for example), as I can't speak for him.
