### ISSUE TITLE
Scribing gnome gets +1 cha, not +1 dex

### ISSUE THREAD

**Issue by malaclypse1** [safety-orange/Imports-for-MPMB-s-Character-Sheet#27]
https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/9f1af22e17fd107a125a376c569dc1c6a5c26193/WotC%20material/all_WotC_published.js#L17443

scores : [0, 0, 0, 2, 0, 1],

**Comment by safety-orange** [comment]
Thank you for reporting this issue, I have now fixed it in commit a97d9b6093e38b17816acae7fda6fef3d074bbb5
