### ISSUE TITLE
Simic hybrid level 5 animal enhancement does not work

### ISSUE THREAD

**Issue by Goosio69** [safety-orange/Imports-for-MPMB-s-Character-Sheet#30]
I have recently picked up a newer version of the scripts that includes the WGtE and the GGtR material. However, I am unable to progress the Simic Hybrid beyond level 5. As soon as I level to 5 (or higher), and no matter the class, the sheet gets stuck with the message "updating simic hybrid 's animal enhancement" and the racial options all disappear (blank as per image below). I cannot update hitpoints or class features until I save and close. If I reopen the sheet the racial options are back but I cannot add the level 5 racial features of the simic hybrid as there are no options beyond the level 1 racial features. 
I am using the latest version of the MPMB character sheet I could find, and the latest scripts for all official WoTC material (no unearthed arcana).
"MPMB's Character Record Sheet (v12.999) [Printer Friendly - Redesign].pdf"
Can you please fix this as I am very keen on making my vampire-bat flavored simic hybrid work!
Thanks,
Paul
![animal enhancement](https://user-images.githubusercontent.com/47495208/52532485-e5768f80-2d8a-11e9-82d1-9f82e0515716.jpg)

**Comment by safety-orange** [comment]
Thank you for reporting this issue. This error only seems to appear when importing the published books, but not the UA articles. The GGtR code for the Simic Hybrid was erroneously referring to the Simic Hybrid from the UA: Races of Ravnica article. I have now fixed it with commit 4288be7b076221e78df42e16e97db3c2f40f4339
