### ISSUE TITLE
Dragonmark, Handling (Human) is Incomplete

### ISSUE THREAD

**Issue by apk24** [safety-orange/Imports-for-MPMB-s-Character-Sheet#31]
Missing the following trait from Dragonmark of Handling:

The Bigger They Are: When you cast a spell that affects only beasts, it also affects monstrosities with an Intelligence score of 3 or lower.

**Comment by safety-orange** [comment]
I guess I totally missed that feature when transcribing the Dragonmark races. Thank you for reporting it, the fix is now pushed with commit b457eafcb3565ce6f7df0293dd207f026214f1cd

**Comment by apk24** [comment]
Thanks, really appreciate all the work you've put into this.
