### ISSUE TITLE
Dragonmark, Finding (Human) missing from all_WotC_published

### ISSUE THREAD

**Issue by apk24** [safety-orange/Imports-for-MPMB-s-Character-Sheet#32]
I was wondering if it was intentional to leave out the human variant of this Dragonmark? AFAIK it's the only Dragonmark with two allowed races. Option first listed in WgtE 90, described in detail on 97. 

Thanks, appreciate all your work.

**Comment by safety-orange** [comment]
The option is not missing. When the [UA: Dragonmarks](https://media.wizards.com/2018/dnd/downloads/UA_Dragonmarks.pdf) came out in September 2018, the Human version of Mark of Finding was dropped by WotC. Only the first version of [Wayfinder's Guide to Eberron on DMs Guild](https://www.dmsguild.com/product/247882/) had it listed as an option for humans, but this was removed in its later updates. Just go ahead and download it again from DMs Guild and you'll see the the dragonmark of finding is only listed for half-orcs.

Originally, I had the human finding dragonmark in the script, but removed it as it was clear that it was not the intention of WotC. You can probably find it if you go back in the commit history.
