### ISSUE TITLE
Dueling Fighting Style error

### ISSUE THREAD

**Issue by DarkPhoenixxy** [safety-orange/Imports-for-MPMB-s-Character-Sheet#33]
Dueling Fighting Style of College of Swords bard (and probably Fighter) apply bonus to Polearm Butt Attack from Polarm Master feat.

**Comment by safety-orange** [comment]
The Dueling Fighting Style is not part of this GitHub repo, so I can't change how it works.

Unforunately, the Polearm Butt Attack can be made both with weapons that are one-handed (quarterstaff, spear) as well as some that are two-handed (glaive, halberd), so it might well be applicable to add the bonus damage from the Dueling Fighting Style.

The Dueling Fighting Style looks for the text "Two-handed" in the description of a weapon. So you will have to add that to make the Polearm Butt Attack not be eligible for the Dueling Fighting Style.
