### ISSUE TITLE
Suggestions / edits for "all_WotC_published.js" v13 Artificer

### ISSUE THREAD

**Issue by Goosio69** [safety-orange/Imports-for-MPMB-s-Character-Sheet#36]
Hi,
I have just downloaded your latest "all_WotC_published.js" for v13 (using on beta 22). Loving the v13 sheet - lightning quick for spell page generation! Well worth the Patreon subscription upgrade from v12.99!
Thank you for including the latest E:RLW Artificer in your latest update - I have been eagerly awaiting that.
I noticed some minor errors in the Artificer sheet. I am not sure how to track the changes made (and I made a couple of extra personal preference changes) so I have just reattached the "all_WotC_published.js" and have put a note //Goosio where I modified the script with the description. File attached.
Suggested changes are:
-Infuse item "extra choices" - added "(prereq: level 6 artificer)" to Homunculus Servant 
-Homunculus Servant option - added "(prereq: level 6 artificer)" and "prereqeval" for level 6
-Battle Smith subclassfeature3.1 - added "calcChanges" for int modifier use
-Battle Smith subclassfeature3.2 - corrected "iron" to "steel" in the text, and removed "cannon" from "removeeval"
-Battle Smith subclassfeature9 - corrected "Eldritch Cannon" to "Steel Defender" for both the "eval" and "removeeval" functions (correctly adds arcane jolt on steel defender now)
-Battle Smith subclassfeature15 - corrected "Eldritch Cannon" to "Steel Defender" for both the "eval" and "removeeval" functions (correctly updates arcane jolt on steel defender now)
-CreatureList[Homunculus Servant] - corrected "Creator" to "Might of the Master" and added "Evasion" to the traits
-CreatureList[Eldritch Cannon] - corrected "Creator" to "Might of the Master"
-CreatureList[Steel Defender] - corrected "Creator" to "Might of the Master".
Keep up the awesome work! 
Paul
[all_WotC_published.Goosio.zip](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/files/3983304/all_WotC_published.Goosio.zip)

**Comment by safety-orange** [comment]
Thank you very much for tracking down these bugs and giving suggestions for the changes. That made fixing them a breeze! I incorporated these changes in the latest commit 51496c3610ad61406fe813794d966510fbe293a4

The only thing I didn't change was the Creator feature of the artificer constructs, as Might of the Master is really only about the proficiency bonus.
