### ISSUE TITLE
'Battle Ready' feature of Battle Smith is just called 'Battle Ready'

### ISSUE THREAD

**Issue by Smashman** [safety-orange/Imports-for-MPMB-s-Character-Sheet#37]
https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/507d1949ef40a33a67faddbd3dd86e9e3a024cf2/WotC%20material/v13/pub_20191119_ERftLW.js#L2386

Not sure where "Battle Ready & Battle Ready" came from!

**Comment by safety-orange** [comment]
Thank you for pointing out that mistake. It is meant to say "Battle Ready & Tool Proficiency", but I screwed up with the copy-pasting when merging those two together ;)
It is fixed in commit 05d8e59a7351c3328abf34775182bcf13dfc7eb5
