### ISSUE TITLE
All Elf subraces are Wood Elf

### ISSUE THREAD

**Issue by Dilbao** [safety-orange/Imports-for-MPMB-s-Character-Sheet#4]
When I choose any Elf subrace, such as Drow or Eladrin, I am getting Wood Elf details. However High Elf is working fine.

I'm using v12.999 with latest script from github.

**Comment by safety-orange** [comment]
Thank you for reporting this! I fixed it in [the UA script here](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/commit/ff2da402bf044136751f4477fa7c3f8b2d16a51b), but I won't be able to update the all_* script on mobile, That will have to wait until January.
