### ISSUE TITLE
Longsword populating twice

### ISSUE THREAD

**Issue by Shwaffle** [safety-orange/Imports-for-MPMB-s-Character-Sheet#49]
User reporting via Discord that Longsword is populating twice when [this source](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/master/WotC%20material/ps_20170705_Amonkhet.js) is loaded.

> Okay, It's in the Amonkhet coding. Using a level 3 kensei monk for the Choose Feature button to include the list of weapons. With the Amonkhet source material loaded it adds an additional longsword in the list. The extra longsword even persists after taking the Amonkhet out of the automation.
It even adds it to the generic magic items.
There are two longswords in the list
https://media.discordapp.net/attachments/537816184574181396/722984684191088670/Capture.PNG?width=333&height=664

**Comment by safety-orange** [comment]
Thanks for reporting! Fixed in commit 1adef42903b9b6b8b848f299f3f203759ddabe02 for the v13 version of that script. The v12.999 version of that script will continue to give an issue as it is not meant to be used with Magic Items.
