### ISSUE TITLE
Theurgy issiue 

### ISSUE THREAD

**Issue by SirServ** [safety-orange/Imports-for-MPMB-s-Character-Sheet#5]
When I pick wizard, I cannot pick Theurgy from the subclass list. No matter what components I load/unload.

**Comment by safety-orange** [comment]
This seems to be an error in the RunFunctionAtEnd in the MPMB sheets, I can't fix that here, but I sent a message to MPMB notifying him of it. Knowing MPMB, you can expect it to be fixed in the next version of the sheets.
