### ISSUE TITLE
Way of Mercy monk Hands of Healing/Harm not showing on character sheet

### ISSUE THREAD

**Issue by malaclypse1** [safety-orange/Imports-for-MPMB-s-Character-Sheet#51]
From ua_20200114_Subclasses-Part-1.js Hands of Healing and Hands of Harm (way of mercy 3) are not being added to the character sheet. Version 13.0.0. Beta30

**Comment by Smashman** [comment]
Have you enabled the source in the source dialog? By default, UA is not enabled.

**Comment by safety-orange** [comment]
For me they are correctly added to the third-page notes section (and displayed in the Changes Dialog as such). Can you please walk me through how to reproduce the issue that those class features don't show up at all?

**Comment by malaclypse1** [comment]
Interesting. I had tried changing subclass several times and could not get hands of X to show. I tried with a new blank character sheet and it shows. Now it is. I Tried switching subclasses away from and back to way of mercy on the original and can't reproduce (the hands of X abilities are now showing). If I can get it to happen again I will take screenshots and save a copy of the 'broken' pdf.
