### ISSUE TITLE
Revided Ranger needs XGtE ranger sub-classes

### ISSUE THREAD

**Issue by adamdva** [safety-orange/Imports-for-MPMB-s-Character-Sheet#6]
ua_20160912_The-Ranger,-Revised.js should include or link in the Ranger sub classes from Xanathar's Guide.

**Comment by safety-orange** [comment]
Xanathar's Guide to Everything has no rules for the revised ranger, nor are there any rules by WotC for adding XGtE subclasses to the revised ranger. However, they are indeed fairly easy to make available for the revised ranger, so I think this request is a good one, even though it is formulated as a demand.

**Comment by safety-orange** [comment]
[This has been added now](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/commit/faba1aed17cf34e1a97a0cc966803059762430d0)!
