### ISSUE TITLE
Improved Pact weapon does not convey a +1 bonus

### ISSUE THREAD

**Issue by Smashman** [safety-orange/Imports-for-MPMB-s-Character-Sheet#7]
![image](https://user-images.githubusercontent.com/2972388/34494030-61897a44-efe6-11e7-93d6-3147239e43db.png)

As you can see above, the 'Pact' Longsword does not have a +1 to damage and attack rolls when I have Improved Pact Weapon selected as an Evocation.

Strength and Charisma are both set to 17 (+3).

**Comment by safety-orange** [comment]
Thank you for reporting this issue, I have fixed it in [this commit](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/commit/9608a1a889212e5e64a647442eb96d93af64fe27).
