### ISSUE TITLE
Sidekick Expert class

### ISSUE THREAD

**Issue by gloaf01** [safety-orange/Imports-for-MPMB-s-Character-Sheet#71]
The sidekick Expert class doesn't load the lv 6 feature Coordinated Strike, and loads the lv 11 feature Inspired Help at lv 10. It also gives you the option for all 4 Expertise selections at lv 10 when you only have 2 at that time.

**Comment by Smashman** [comment]
The version in this repo is the Unearthed Arcana released in September 2018 found here: https://dnd.wizards.com/articles/unearthed-arcana/sidekicks

You had to have enabled that Unearthed Arcana content to have even come across it, as UA content is not enabled by default.

The version that you are describing is from Tasha's Cauldron of Everything which has not been transcribed by @safety-orange. There is an effort to transcribe TCE on the Discord, however I am not sure Sidekicks have been attempted. You could enquire there: https://discord.com/invite/Qjq9Z5Q

Thank you.

**Comment by gloaf01** [comment]
Ah my apologies still new to all this stuff thank you for clarifying.
