### ISSUE TITLE
Soldier background personality traits and flaws slightly incorrect?

### ISSUE THREAD

**Issue by Smashman** [safety-orange/Imports-for-MPMB-s-Character-Sheet#8]
Hey, so I was creating a character with a Soldier background and I noticed that the personality trait stated as "I can stare down **a hell hound** without flinching" is listed as ["I can stare down **an owlbear** without flinching"](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/c5458b074e6e0c37c1ca44778edc0c22629f4f72/WotC%20material/pub_20140818_PHB.js#L2660).
Also, the flaw "I **obey** the law, even if the law causes **misery**." says ["I **uphold** the law, even if the law causes **suffering**"](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/blob/c5458b074e6e0c37c1ca44778edc0c22629f4f72/WotC%20material/pub_20140818_PHB.js#L2698).

Is there a reason for these differences that I am not seeing? Errata perhaps?
The above aside, I much prefer your versions.

Thanks.

**Comment by safety-orange** [comment]
My best guess is that this is something that MPMB did to avoid copyright issues back when first starting to automate the sheet.

If you are interested, you could go over the PHB backgrounds and correct these minor differences with the PHB text. I expect that this was only done for the PHB backgrounds.
